queue:
  name: Hosted VS2017
  demands: npm


steps:
- task: Npm@1
  inputs:
    command: install
    workingDir: 'react-app'
    verbose: false

- task: Npm@1
  inputs:
    command: install
    workingDir: 'functions'
    verbose: false

- task: Npm@1
  inputs:
    command: custom
    verbose: false
    workingDir: 'react-app'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: custom
    verbose: false
    customCommand: 'install firebase-tools -g'

- task: CmdLine@1
  inputs:
    filename: 'firebase'
    arguments: 'deploy --token $(FIREBASE_TOKEN)'

