version: "3"
services:
  mongo:
    image: mongo
    expose: 
      - 27059
    ports: 
      - "27059:27017"
    volumes:
      - mongodata:/data/db

  mongoexpress:
    image: mongo-express
    ports: 
      - "6000:8081"
    links:
      - mongo

volumes:
  mongodata: